# Fonts
disable_ligatures always
font_family family="JetBrainsMonoNL Nerd Font Mono"
font_size 12

# Text cursor
cursor_shape beam
cursor_beam_thickness 1.8

# Mouse
url_style double

# Audio
enable_audio_bell no

# Window layout
hide_window_decorations yes
window_padding_width 8

# Tab bar
tab_bar_style powerline
active_tab_background #98c379
inactive_tab_foreground #000000
inactive_tab_background #e06c75

# Color scheme
background_opacity 0.9

# OS tweaks
linux_display_server wayland

# Clipboard
map f1 copy_to_buffer a
map f2 paste_from_buffer a
map f3 copy_to_buffer b
map f4 paste_from_buffer b

# Keybindings
map ctrl+shift+z toggle_layout stack
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
map ctrl+down neighboring_window down
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
