$font = Monospace

general {
    hide_cursor = false
}

# Fingerprint authentication
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    color = rgba(17, 17, 17, 1.0)
}

input-field {
    monitor =
    size = 380, 60
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -120
    halign = center
    valign = center
}

# Username
label {
    monitor =
    text = $USER
    text_align = center
    font_size = 28
    font_family = $font Bold
    position = 0, 0
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:60000] date +"%a %e %b %Y %R" # update every 60 seconds
    text_align = center
    font_size = 32
    font_family = $font Bold
    position = 0, -80
    halign = center
    valign = top
}

# Keyboard layout
label {
    monitor =
    text =   $LAYOUT[us,latam]
    text_align = center
    font_family = $font
    font_size = 16
    position = 0, -180
    halign = center
    valign = center
    onclick = hyprctl switchxkblayout all next
}

# Battery
label {
    monitor =
    color = rgba(140, 192, 190, 1.0)
    text = cmd[update:60000] echo -n "$(cat /sys/class/power_supply/BAT0/capacity)%"
    text_align = center
    font_family = $font Bold
    font_size = 24
    position = -80, -80
    halign = right
    valign = top
}

