# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$directory$git_branch${env_var.VIRTUAL_ENV_PROMPT}$jobs$cmd_duration$username$character
'''

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cmd_duration]
format = '[$duration]($style) '
min_time = 5000
style = 'bold purple'

[cobol]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[cpp]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[directory]
read_only = ' '
truncate_to_repo = false
truncation_length = 0

[direnv]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var.VIRTUAL_ENV_PROMPT]
format = '[$symbol$env_value]($style) '
style = 'bold yellow'
symbol = '󰌠 '
variable = 'VIRTUAL_ENV_PROMPT'

[erlang]
disabled = true

[fennel]
disabled = true

[fortran]
disabled = true

[fossil_branch]
disabled = true

[fossil_metrics]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'bold #ff8000'
symbol = ' '

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[gleam]
disabled = true

[golang]
disabled = true

[gradle]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[hg_state]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[jobs]
number_threshold = 1
symbol_threshold = 1

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[localip]
disabled = true

[lua]
disabled = true

[maven]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[mise]
disabled = true

[mojo]
disabled = true

[nats]
disabled = true

[netns]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[odin]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[os]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pixi]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[quarto]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[status]
disabled = true

[sudo]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[typst]
disabled = true

[username]
aliases = { 'root' = '' }
format = '[$user]($style) '
style_root = 'red'

[vagrant]
disabled = true

[vcs]
disabled = true

[vcsh]
disabled = true

[vlang]
disabled = true

[xmake]
disabled = true

[zig]
disabled = true

[custom]
disabled = true
